// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MMC_Pro_Edition.Models;

[Table("Cities", Schema = "HRM")]
public partial class Cities
{
    [Key]
    public int CityId { get; set; }

    [StringLength(1000)]
    public string CityName { get; set; }

    public int? CountryId { get; set; }

    [ForeignKey("CountryId")]
    [InverseProperty("Cities")]
    public virtual Countries Country { get; set; }

    [InverseProperty("City")]
    public virtual ICollection<LaneAddresses> LaneAddresses { get; set; } = new List<LaneAddresses>();
}