// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MMC_Pro_Edition.Models;

[Table("Countries", Schema = "HRM")]
public partial class Countries
{
    [Key]
    public int CountryId { get; set; }

    [StringLength(1000)]
    public string CountryName { get; set; }

    [InverseProperty("Country")]
    public virtual ICollection<StateProvince> StateProvince { get; set; } = new List<StateProvince>();
}