// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MMC_Pro_Edition.Models;

[Table("Customers", Schema = "HRM")]
public partial class Customers
{
    [Key]
    public int Id { get; set; }

    [StringLength(50)]
    public string FirstName { get; set; }

    [StringLength(50)]
    public string LastName { get; set; }

    [StringLength(50)]
    public string CustomerCode { get; set; }

    public int PersonId { get; set; }

    public bool? IsActive { get; set; }

    [ForeignKey("PersonId")]
    [InverseProperty("Customers")]
    public virtual Persons Person { get; set; }
}