// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MMC_Pro_Edition.Models;

[Table("Department", Schema = "HRM")]
public partial class Department
{
    [Key]
    public int Id { get; set; }

    [StringLength(50)]
    public string Title { get; set; }

    [InverseProperty("Department")]
    public virtual ICollection<Employee> Employee { get; set; } = new List<Employee>();
}