// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MMC_Pro_Edition.Models;

[Table("Employee", Schema = "HRM")]
public partial class Employee
{
    [Key]
    public int EmployeeId { get; set; }

    [StringLength(50)]
    public string EmployeeCode { get; set; }

    public int? DepartmentId { get; set; }

    public int? DesignationId { get; set; }

    [Column(TypeName = "date")]
    public DateTime? CreatedOn { get; set; }

    public bool? IsActive { get; set; }

    public int? PersonId { get; set; }

    [ForeignKey("DepartmentId")]
    [InverseProperty("Employee")]
    public virtual Department Department { get; set; }

    [ForeignKey("DesignationId")]
    [InverseProperty("Employee")]
    public virtual EmployeeDesignation Designation { get; set; }

    [ForeignKey("PersonId")]
    [InverseProperty("Employee")]
    public virtual Persons Person { get; set; }
}