// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MMC_Pro_Edition.Models;

[Table("LaneAddresses", Schema = "HRM")]
public partial class LaneAddresses
{
    [Key]
    public int AddressId { get; set; }

    [StringLength(2000)]
    public string LaneAddressOne { get; set; }

    [StringLength(2000)]
    public string LaneAddressTwo { get; set; }

    [StringLength(2000)]
    public string Area { get; set; }

    [StringLength(2000)]
    public string FamousPlace { get; set; }

    public int? PersonId { get; set; }

    public int? CityId { get; set; }

    [StringLength(500)]
    public string AddressType { get; set; }

    [ForeignKey("CityId")]
    [InverseProperty("LaneAddresses")]
    public virtual Cities City { get; set; }

    [ForeignKey("PersonId")]
    [InverseProperty("LaneAddresses")]
    public virtual Persons Person { get; set; }
}