// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MMC_Pro_Edition.Models;

[Table("LoginHistory", Schema = "HRM")]
public partial class LoginHistory
{
    [Key]
    public int Id { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastLogin { get; set; }

    public int? LoginUserId { get; set; }

    [ForeignKey("LoginUserId")]
    [InverseProperty("LoginHistory")]
    public virtual LoginUsers LoginUser { get; set; }
}