// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MMC_Pro_Edition.Models;

[Table("LoginUserDeviceDetail", Schema = "HRM")]
public partial class LoginUserDeviceDetail
{
    [Key]
    public int Id { get; set; }

    [StringLength(100)]
    public string DeviceName { get; set; }

    [Column("DeviceIP")]
    [StringLength(100)]
    public string DeviceIp { get; set; }

    public int? LoginUserId { get; set; }

    [ForeignKey("LoginUserId")]
    [InverseProperty("LoginUserDeviceDetail")]
    public virtual LoginUsers LoginUser { get; set; }
}