// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MMC_Pro_Edition.Models;

[Table("LoginUsers", Schema = "HRM")]
public partial class LoginUsers
{
    [Key]
    public int Id { get; set; }

    [StringLength(50)]
    public string UserName { get; set; }

    [StringLength(50)]
    public string Passwords { get; set; }

    public int? PersonId { get; set; }

    public int? SettingsId { get; set; }

    public bool? IsActive { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedOn { get; set; }

    [InverseProperty("Login")]
    public virtual ICollection<AssignedRoles> AssignedRoles { get; set; } = new List<AssignedRoles>();

    [InverseProperty("EmailNavigation")]
    public virtual ICollection<CmsemailSent> CmsemailSent { get; set; } = new List<CmsemailSent>();

    [InverseProperty("LoginUser")]
    public virtual ICollection<Content> Content { get; set; } = new List<Content>();

    [InverseProperty("LoginUser")]
    public virtual ICollection<LoginHistory> LoginHistory { get; set; } = new List<LoginHistory>();

    [InverseProperty("LoginUser")]
    public virtual ICollection<LoginUserDeviceDetail> LoginUserDeviceDetail { get; set; } = new List<LoginUserDeviceDetail>();

    [ForeignKey("PersonId")]
    [InverseProperty("LoginUsers")]
    public virtual Persons Person { get; set; }

    [InverseProperty("LoginUser")]
    public virtual ICollection<Reviews> Reviews { get; set; } = new List<Reviews>();

    [ForeignKey("SettingsId")]
    [InverseProperty("LoginUsers")]
    public virtual Settings Settings { get; set; }
}