// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MMC_Pro_Edition.Models;

[Table("Persons", Schema = "HRM")]
public partial class Persons
{
    [Key]
    public int Id { get; set; }

    [StringLength(50)]
    public string FirstName { get; set; }

    [StringLength(50)]
    public string LastName { get; set; }

    [StringLength(50)]
    public string MobileNumber { get; set; }

    [Column("CNIC")]
    [StringLength(50)]
    public string Cnic { get; set; }

    [StringLength(10)]
    public string SocialSecurity { get; set; }

    [StringLength(50)]
    public string Email { get; set; }

    [Column("ImageURL")]
    public string ImageUrl { get; set; }

    [InverseProperty("Person")]
    public virtual ICollection<Customers> Customers { get; set; } = new List<Customers>();

    [InverseProperty("Person")]
    public virtual ICollection<Employee> Employee { get; set; } = new List<Employee>();

    [InverseProperty("Person")]
    public virtual ICollection<LaneAddresses> LaneAddresses { get; set; } = new List<LaneAddresses>();

    [InverseProperty("Person")]
    public virtual ICollection<LoginUsers> LoginUsers { get; set; } = new List<LoginUsers>();

    [InverseProperty("Person")]
    public virtual ICollection<Supplier> Supplier { get; set; } = new List<Supplier>();
}