// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MMC_Pro_Edition.Models;

[Table("StateProvince", Schema = "HRM")]
public partial class StateProvince
{
    [Key]
    public int StateProvinceId { get; set; }

    [StringLength(1000)]
    public string StateProvinceName { get; set; }

    public int? CountryId { get; set; }

    [InverseProperty("StateProvince")]
    public virtual ICollection<Cities> Cities { get; set; } = new List<Cities>();

    [ForeignKey("CountryId")]
    [InverseProperty("StateProvince")]
    public virtual Countries Country { get; set; }
}