// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MMC_Pro_Edition.Models;

[Table("SupplierContact", Schema = "HRM")]
public partial class SupplierContact
{
    [Key]
    public int SpplierContactId { get; set; }

    public int? PersonId { get; set; }

    public int? SupplierId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedOn { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ModifiedOn { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    [ForeignKey("PersonId")]
    [InverseProperty("SupplierContact")]
    public virtual Persons Person { get; set; }

    [ForeignKey("SupplierId")]
    [InverseProperty("SupplierContact")]
    public virtual Supplier Supplier { get; set; }
}