// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MMC_Pro_Edition.Models;

[Table("Supplier", Schema = "HRM")]
public partial class Supplier
{
    [Key]
    public int SupplierId { get; set; }

    [StringLength(500)]
    public string SupplierCode { get; set; }

    [Column(TypeName = "date")]
    public DateTime? CreatedOn { get; set; }

    [Column("NTN")]
    [StringLength(100)]
    public string Ntn { get; set; }

    [StringLength(500)]
    public string CompanyLogo { get; set; }

    public int? PersonId { get; set; }

    public bool? IsActive { get; set; }

    [ForeignKey("PersonId")]
    [InverseProperty("Supplier")]
    public virtual Persons Person { get; set; }
}