// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MMC_Pro_Edition.Models;

[Table("UserAssignedBranches", Schema = "HRM")]
public partial class UserAssignedBranches
{
    [Key]
    [Column("UserAssignedBranches")]
    public int UserAssignedBranches1 { get; set; }

    public int? LoginUserId { get; set; }

    public Guid? BranchId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ModifiedOn { get; set; }

    public bool? IsActive { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedOn { get; set; }

    public bool? IsDeleted { get; set; }

    public int? Createdby { get; set; }

    [ForeignKey("LoginUserId")]
    [InverseProperty("UserAssignedBranches")]
    public virtual LoginUsers LoginUser { get; set; }
}