// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace MMC_Pro_Edition.Models;

public partial class Onedb : DbContext
{
    public Onedb(DbContextOptions<Onedb> options)
        : base(options)
    {
    }

    public virtual DbSet<AssignedRoles> AssignedRoles { get; set; }

    public virtual DbSet<CmsContentSharedCategory> CmsContentSharedCategory { get; set; }

    public virtual DbSet<CmsEmail> CmsEmail { get; set; }

    public virtual DbSet<CmsEmailAttachments> CmsEmailAttachments { get; set; }

    public virtual DbSet<Content> Content { get; set; }

    public virtual DbSet<ContentCategory> ContentCategory { get; set; }

    public virtual DbSet<ContentType> ContentType { get; set; }

    public virtual DbSet<Customers> Customers { get; set; }

    public virtual DbSet<Department> Department { get; set; }

    public virtual DbSet<Employee> Employee { get; set; }

    public virtual DbSet<EmployeeDesignation> EmployeeDesignation { get; set; }

    public virtual DbSet<FileManager> FileManager { get; set; }

    public virtual DbSet<LoginHistory> LoginHistory { get; set; }

    public virtual DbSet<LoginUserDeviceDetail> LoginUserDeviceDetail { get; set; }

    public virtual DbSet<LoginUsers> LoginUsers { get; set; }

    public virtual DbSet<Persons> Persons { get; set; }

    public virtual DbSet<Roles> Roles { get; set; }

    public virtual DbSet<Settings> Settings { get; set; }

    public virtual DbSet<Supplier> Supplier { get; set; }

    public virtual DbSet<Website> Website { get; set; }

    public virtual DbSet<WebsiteData> WebsiteData { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AssignedRoles>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.Login).WithMany(p => p.AssignedRoles).HasConstraintName("FK_AssignedRoles_LoginUsers");

            entity.HasOne(d => d.Role).WithMany(p => p.AssignedRoles).HasConstraintName("FK_AssignedRoles_Roles");
        });

        modelBuilder.Entity<CmsContentSharedCategory>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.Category).WithMany(p => p.CmsContentSharedCategory).HasConstraintName("FK_CmsContentSharedCategory_ContentCategory");

            entity.HasOne(d => d.Content).WithMany(p => p.CmsContentSharedCategory).HasConstraintName("FK_CmsContentSharedCategory_Content");
        });

        modelBuilder.Entity<CmsEmail>(entity =>
        {
            entity.Property(e => e.EmailId).ValueGeneratedNever();

            entity.HasOne(d => d.Website).WithMany(p => p.CmsEmail).HasConstraintName("FK_CmsEmail_Website");
        });

        modelBuilder.Entity<CmsEmailAttachments>(entity =>
        {
            entity.Property(e => e.AttachmentId).ValueGeneratedNever();

            entity.HasOne(d => d.Email).WithMany(p => p.CmsEmailAttachments).HasConstraintName("FK_CmsEmailAttachments_CmsEmail");
        });

        modelBuilder.Entity<Content>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.ContentType).WithMany(p => p.Content).HasConstraintName("FK_Content_ContentType");

            entity.HasOne(d => d.WebSite).WithMany(p => p.Content).HasConstraintName("FK_Content_Website");
        });

        modelBuilder.Entity<ContentCategory>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.Type).WithMany(p => p.ContentCategory)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ContentCategory_ContentType");
        });

        modelBuilder.Entity<ContentType>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
        });

        modelBuilder.Entity<Customers>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.Person).WithMany(p => p.Customers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Customers_Persons");
        });

        modelBuilder.Entity<Department>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_Department_1");

            entity.Property(e => e.Id).ValueGeneratedNever();
        });

        modelBuilder.Entity<Employee>(entity =>
        {
            entity.Property(e => e.EmployeeId).ValueGeneratedNever();

            entity.HasOne(d => d.Department).WithMany(p => p.Employee).HasConstraintName("FK_Employee_Department");

            entity.HasOne(d => d.Designation).WithMany(p => p.Employee).HasConstraintName("FK_Employee_EmployeeDesignation");

            entity.HasOne(d => d.Person).WithMany(p => p.Employee).HasConstraintName("FK_Employee_Persons");
        });

        modelBuilder.Entity<EmployeeDesignation>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
        });

        modelBuilder.Entity<FileManager>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.Content).WithMany(p => p.FileManager).HasConstraintName("FK_FileManager_Content");
        });

        modelBuilder.Entity<LoginHistory>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.LoginUser).WithMany(p => p.LoginHistory).HasConstraintName("FK_LoginHistory_LoginUsers");
        });

        modelBuilder.Entity<LoginUserDeviceDetail>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.LoginUser).WithMany(p => p.LoginUserDeviceDetail).HasConstraintName("FK_LoginUserDeviceDetail_LoginUsers");
        });

        modelBuilder.Entity<LoginUsers>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.Person).WithMany(p => p.LoginUsers).HasConstraintName("FK_LoginUsers_Persons");

            entity.HasOne(d => d.Settings).WithMany(p => p.LoginUsers).HasConstraintName("FK_LoginUsers_Settings");
        });

        modelBuilder.Entity<Persons>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.SocialSecurity).IsFixedLength();
        });

        modelBuilder.Entity<Roles>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
        });

        modelBuilder.Entity<Settings>(entity =>
        {
            entity.Property(e => e.SettingsId).ValueGeneratedNever();
        });

        modelBuilder.Entity<Supplier>(entity =>
        {
            entity.Property(e => e.SupplierId).ValueGeneratedNever();

            entity.HasOne(d => d.Person).WithMany(p => p.Supplier).HasConstraintName("FK_Supplier_Persons");
        });

        modelBuilder.Entity<Website>(entity =>
        {
            entity.HasKey(e => e.WebsiteId).HasName("PK_InfoValues");

            entity.Property(e => e.WebsiteId).ValueGeneratedNever();
        });

        modelBuilder.Entity<WebsiteData>(entity =>
        {
            entity.Property(e => e.WebsiteDataId).ValueGeneratedNever();

            entity.HasOne(d => d.Website).WithMany(p => p.WebsiteData)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_WebsiteData_Website");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}