// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MMC_Pro_Edition.Models;

[Table("FileManager", Schema = "MEDIA")]
public partial class FileManager
{
    [Key]
    public int Id { get; set; }

    [Column("URL")]
    [StringLength(1000)]
    public string Url { get; set; }

    [StringLength(1000)]
    public string Caption { get; set; }

    public int? Priority { get; set; }

    public int? ContentId { get; set; }

    [ForeignKey("ContentId")]
    [InverseProperty("FileManager")]
    public virtual Content Content { get; set; }
}