// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MMC_Pro_Edition.Models;

[Table("CmsContentSharedCategory", Schema = "WEBCMS")]
public partial class CmsContentSharedCategory
{
    [Key]
    public int Id { get; set; }

    public int? ContentId { get; set; }

    public int? CategoryId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedOn { get; set; }

    [ForeignKey("CategoryId")]
    [InverseProperty("CmsContentSharedCategory")]
    public virtual ContentCategory Category { get; set; }

    [ForeignKey("ContentId")]
    [InverseProperty("CmsContentSharedCategory")]
    public virtual Content Content { get; set; }
}