// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MMC_Pro_Edition.Models;

[Table("CmsEmail", Schema = "WEBCMS")]
public partial class CmsEmail
{
    [Key]
    public int EmailId { get; set; }

    public int? WebsiteId { get; set; }

    [StringLength(500)]
    public string EmailSubject { get; set; }

    [StringLength(500)]
    public string EmailSender { get; set; }

    public string EmailBody { get; set; }

    [Column(TypeName = "date")]
    public DateTime? DateCreated { get; set; }

    [StringLength(500)]
    public string FirstName { get; set; }

    [StringLength(500)]
    public string LastName { get; set; }

    [StringLength(500)]
    public string FullName { get; set; }

    [StringLength(500)]
    public string Mobile { get; set; }

    [StringLength(500)]
    public string LandLine { get; set; }

    public bool? IsSend { get; set; }

    [StringLength(500)]
    public string StatusMessage { get; set; }

    [InverseProperty("Email")]
    public virtual ICollection<CmsEmailAttachments> CmsEmailAttachments { get; set; } = new List<CmsEmailAttachments>();

    [ForeignKey("WebsiteId")]
    [InverseProperty("CmsEmail")]
    public virtual Website Website { get; set; }
}