// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MMC_Pro_Edition.Models;

[Table("CmsEmailAttachments", Schema = "WEBCMS")]
public partial class CmsEmailAttachments
{
    [Key]
    public int AttachmentId { get; set; }

    public int? EmailId { get; set; }

    [Column("AttachmentURL")]
    public string AttachmentUrl { get; set; }

    [ForeignKey("EmailId")]
    [InverseProperty("CmsEmailAttachments")]
    public virtual CmsEmail Email { get; set; }
}