// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MMC_Pro_Edition.Models;

[Table("CMSEmailSent", Schema = "WEBCMS")]
public partial class CmsemailSent
{
    [Key]
    public int EmailSentId { get; set; }

    [Required]
    [StringLength(255)]
    public string ToEmailAddress { get; set; }

    [Required]
    [StringLength(255)]
    public string FromEmailAddress { get; set; }

    [Required]
    [StringLength(500)]
    public string Subject { get; set; }

    [Required]
    public string Body { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime SentDateTime { get; set; }

    public bool IsSent { get; set; }

    public bool IsRead { get; set; }

    public int? UserId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedDate { get; set; }

    public int? EmailId { get; set; }

    [ForeignKey("EmailId")]
    [InverseProperty("CmsemailSent")]
    public virtual CmsEmail Email { get; set; }

    [ForeignKey("EmailId")]
    [InverseProperty("CmsemailSent")]
    public virtual LoginUsers EmailNavigation { get; set; }
}