// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MMC_Pro_Edition.Models;

[Table("CMSLeadContacts", Schema = "WEBCMS")]
public partial class CmsleadContacts
{
    [Key]
    public int LeadContactId { get; set; }

    [StringLength(500)]
    public string FirstName { get; set; }

    [StringLength(500)]
    public string LastName { get; set; }

    [StringLength(500)]
    public string Mobile { get; set; }

    [StringLength(500)]
    public string Email { get; set; }

    [StringLength(500)]
    public string FullName { get; set; }
}