// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MMC_Pro_Edition.Models;

[Table("ContentCategory", Schema = "WEBCMS")]
public partial class ContentCategory
{
    [Key]
    public int Id { get; set; }

    [StringLength(501)]
    public string Name { get; set; }

    public int TypeId { get; set; }

    [StringLength(50)]
    public string CreatedOn { get; set; }

    [StringLength(501)]
    public string Slug { get; set; }

    [InverseProperty("Category")]
    public virtual ICollection<CmsContentSharedCategory> CmsContentSharedCategory { get; set; } = new List<CmsContentSharedCategory>();

    [ForeignKey("TypeId")]
    [InverseProperty("ContentCategory")]
    public virtual ContentType Type { get; set; }
}