// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MMC_Pro_Edition.Models;

[Table("ContentType", Schema = "WEBCMS")]
public partial class ContentType
{
    [Key]
    public int Id { get; set; }

    [StringLength(50)]
    public string Name { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedOn { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ModifiedOn { get; set; }

    [StringLength(100)]
    public string TypeSlug { get; set; }

    [InverseProperty("ContentType")]
    public virtual ICollection<Content> Content { get; set; } = new List<Content>();

    [InverseProperty("Type")]
    public virtual ICollection<ContentCategory> ContentCategory { get; set; } = new List<ContentCategory>();
}