// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MMC_Pro_Edition.Models;

[Table("Content", Schema = "WEBCMS")]
public partial class Content
{
    [Key]
    public int Id { get; set; }

    [StringLength(1000)]
    public string Name { get; set; }

    [StringLength(1000)]
    public string Tagline { get; set; }

    public string OverView { get; set; }

    [StringLength(500)]
    public string VideoLink { get; set; }

    [StringLength(1000)]
    public string Note { get; set; }

    public string Description { get; set; }

    [StringLength(500)]
    public string ImageSource { get; set; }

    [StringLength(500)]
    public string Thumbnail { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedOn { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ModifiedOn { get; set; }

    public int? WebSiteId { get; set; }

    public int? ContentTypeId { get; set; }

    [StringLength(1500)]
    public string OtherTitle { get; set; }

    [StringLength(1500)]
    public string MetaDescription { get; set; }

    public string ShortDescription { get; set; }

    public string OtherShortDescription { get; set; }

    public string OtherDescription { get; set; }

    public int? Priority { get; set; }

    [StringLength(50)]
    public string Icon { get; set; }

    [StringLength(1500)]
    public string MetaTitle { get; set; }

    [StringLength(500)]
    public string HeaderPhoto { get; set; }

    [StringLength(1000)]
    public string ContentSlug { get; set; }

    [Column("FwdURL")]
    [StringLength(800)]
    public string FwdUrl { get; set; }

    [StringLength(1500)]
    public string MetaKeyword { get; set; }

    public int? ParentId { get; set; }

    [Column(TypeName = "date")]
    public DateTime? Date { get; set; }

    public int? LoginUserId { get; set; }

    [Column("IPAddress")]
    [StringLength(500)]
    public string Ipaddress { get; set; }

    public bool? IsPublished { get; set; }

    [InverseProperty("Content")]
    public virtual ICollection<CmsContentSharedCategory> CmsContentSharedCategory { get; set; } = new List<CmsContentSharedCategory>();

    [ForeignKey("ContentTypeId")]
    [InverseProperty("Content")]
    public virtual ContentType ContentType { get; set; }

    [InverseProperty("Content")]
    public virtual ICollection<FileManager> FileManager { get; set; } = new List<FileManager>();

    [InverseProperty("LinkedContent")]
    public virtual ICollection<LinkedContentItems> LinkedContentItems { get; set; } = new List<LinkedContentItems>();

    [ForeignKey("LoginUserId")]
    [InverseProperty("Content")]
    public virtual LoginUsers LoginUser { get; set; }

    [InverseProperty("Content")]
    public virtual ICollection<Reviews> Reviews { get; set; } = new List<Reviews>();

    [ForeignKey("WebSiteId")]
    [InverseProperty("Content")]
    public virtual Website WebSite { get; set; }
}