// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MMC_Pro_Edition.Models;

[Table("LinkedContentItems", Schema = "WEBCMS")]
public partial class LinkedContentItems
{
    [Key]
    public int LinkedItemId { get; set; }

    public int? LiniedContentId { get; set; }

    public int? ContentId { get; set; }

    public int? Priority { get; set; }

    [ForeignKey("ContentId")]
    [InverseProperty("LinkedContentItems")]
    public virtual Content Content { get; set; }
}