// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MMC_Pro_Edition.Models;

[Table("Reviews", Schema = "WEBCMS")]
public partial class Reviews
{
    [Key]
    public int ReviewId { get; set; }

    [StringLength(1000)]
    public string ReviewComment { get; set; }

    public short? Rating { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedOn { get; set; }

    public int? LoginUserId { get; set; }

    public bool? IsPublished { get; set; }

    public int? ApprovedBy { get; set; }

    [Column("UserIP")]
    [StringLength(50)]
    public string UserIp { get; set; }

    [StringLength(50)]
    public string UserBrowser { get; set; }

    public int? ContentId { get; set; }

    [InverseProperty("Review")]
    public virtual ICollection<Comments> Comments { get; set; } = new List<Comments>();

    [ForeignKey("ContentId")]
    [InverseProperty("Reviews")]
    public virtual Content Content { get; set; }

    [ForeignKey("LoginUserId")]
    [InverseProperty("Reviews")]
    public virtual LoginUsers LoginUser { get; set; }
}