// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MMC_Pro_Edition.Models;

[Table("AssignedRoles", Schema = "SYSTEM")]
public partial class AssignedRoles
{
    [Key]
    public int Id { get; set; }

    public int? RoleId { get; set; }

    public int? LoginId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedOn { get; set; }

    [ForeignKey("LoginId")]
    [InverseProperty("AssignedRoles")]
    public virtual LoginUsers Login { get; set; }

    [ForeignKey("RoleId")]
    [InverseProperty("AssignedRoles")]
    public virtual Roles Role { get; set; }
}