// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MMC_Pro_Edition.Models;

[Table("CMSSettings", Schema = "SYSTEM")]
public partial class Cmssettings
{
    [Key]
    [Column("CMSSettingId")]
    public int CmssettingId { get; set; }

    public bool IsAiEnabled { get; set; }
}