// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MMC_Pro_Edition.Models;

[Table("ErpPermissions", Schema = "SYSTEM")]
public partial class ErpPermissions
{
    [Key]
    public int PermissionId { get; set; }

    public int? UserId { get; set; }

    public bool? CanView { get; set; }

    public bool? CanEdit { get; set; }

    public bool? CanDelete { get; set; }

    public bool? CanCreate { get; set; }

    public int? UrlMenuId { get; set; }

    [ForeignKey("UrlMenuId")]
    [InverseProperty("ErpPermissions")]
    public virtual UrlMenu UrlMenu { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("ErpPermissions")]
    public virtual LoginUsers User { get; set; }
}