// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MMC_Pro_Edition.Models;

[Table("NotificationTypes", Schema = "SYSTEM")]
public partial class NotificationTypes
{
    [Key]
    public int NotificationTypeId { get; set; }

    [StringLength(500)]
    public string NotificationTypeName { get; set; }

    [InverseProperty("NotificationType")]
    public virtual ICollection<Notifications> Notifications { get; set; } = new List<Notifications>();
}