// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MMC_Pro_Edition.Models;

[Table("Notifications", Schema = "SYSTEM")]
[Index("GroupName", Name = "IX_Notifications_GroupName")]
[Index("GroupName", "IsRead", Name = "IX_Notifications_GroupName_IsRead")]
[Index("UserId", Name = "IX_Notifications_UserId")]
[Index("UserId", "IsRead", Name = "IX_Notifications_UserId_IsRead")]
public partial class Notifications
{
    [Key]
    public int Id { get; set; }

    [Required]
    public string Message { get; set; }

    public string Params { get; set; }

    public string UserId { get; set; }

    [StringLength(255)]
    public string GroupName { get; set; }

    public bool IsRead { get; set; }

    public DateTime CreatedAt { get; set; }

    public int? NotificationTypeId { get; set; }

    [ForeignKey("NotificationTypeId")]
    [InverseProperty("Notifications")]
    public virtual NotificationTypes NotificationType { get; set; }
}