// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MMC_Pro_Edition.Models;

[Table("Settings", Schema = "SYSTEM")]
public partial class Settings
{
    [Key]
    public int SettingsId { get; set; }

    public int? ApplicationId { get; set; }

    [Column("ApplicationURL")]
    [StringLength(1000)]
    public string ApplicationUrl { get; set; }

    public bool? IsActive { get; set; }

    public Guid? BranchId { get; set; }

    [StringLength(1000)]
    public string ApplicationName { get; set; }

    [InverseProperty("Settings")]
    public virtual ICollection<LoginUsers> LoginUsers { get; set; } = new List<LoginUsers>();
}