// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MMC_Pro_Edition.Models;

[Table("UrlMenu", Schema = "SYSTEM")]
public partial class UrlMenu
{
    [Key]
    public int UrlMenuId { get; set; }

    [StringLength(50)]
    public string UrlMenuLink { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedOn { get; set; }

    public int? CreatedBy { get; set; }

    [InverseProperty("UrlMenu")]
    public virtual ICollection<ErpPermissions> ErpPermissions { get; set; } = new List<ErpPermissions>();
}