// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MMC_Pro_Edition.Models;

[Table("WebsiteData", Schema = "SYSTEM")]
public partial class WebsiteData
{
    [Key]
    public int WebsiteDataId { get; set; }

    [StringLength(50)]
    public string Title { get; set; }

    [Column("value")]
    [StringLength(50)]
    public string Value { get; set; }

    public int WebsiteId { get; set; }

    [ForeignKey("WebsiteId")]
    [InverseProperty("WebsiteData")]
    public virtual Website Website { get; set; }
}