// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MMC_Pro_Edition.Models;

[Table("Website", Schema = "SYSTEM")]
public partial class Website
{
    [Key]
    public int WebsiteId { get; set; }

    [StringLength(500)]
    public string WebsiteName { get; set; }

    public string WebsiteLogo { get; set; }

    public string WebsiteLogoTwo { get; set; }

    public string FavIcon { get; set; }

    public string WebsiteDescription { get; set; }

    public string WebsiteTitle { get; set; }

    public string SupportEmail { get; set; }

    [InverseProperty("Website")]
    public virtual ICollection<CmsEmail> CmsEmail { get; set; } = new List<CmsEmail>();

    [InverseProperty("WebSite")]
    public virtual ICollection<Content> Content { get; set; } = new List<Content>();

    [InverseProperty("Website")]
    public virtual ICollection<WebsiteData> WebsiteData { get; set; } = new List<WebsiteData>();
}